[build]
command = "quarto render"
publish = "_site"

[build.environment]
QUARTO_VERSION = "1.4.550"

[context]
[context.branch-deploy]
command = "quarto render"
[context.deploy-preview]
command = "quarto render"
[context.production]
[context.production.environment]
QUARTO_ENV = "production"
